openapi: 3.0.1
info:
  title: API Microservicio Factura
  description: API para gestionar facturas y calcular totales facturados
  version: 1.0.0
servers:
  - url: http://localhost:8003

paths:
  /facturas:
    post:
      summary: Crear una nueva factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'

    get:
      summary: Obtener todas las facturas
      responses:
        '200':
          description: Lista de facturas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'

  /facturas/{id}:
    get:
      summary: Obtener factura por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Factura encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          description: Factura no encontrada

    put:
      summary: Actualizar factura por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          description: Factura no encontrada

    delete:
      summary: Eliminar factura por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Factura eliminada
        '404':
          description: Factura no encontrada

  /facturas/total:
    get:
      summary: Obtener total facturado en un periodo
      parameters:
        - in: query
          name: anio
          required: true
          schema:
            type: integer
        - in: query
          name: mesInicio
          required: true
          schema:
            type: integer
        - in: query
          name: mesFin
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Total facturado
          content:
            application/json:
              schema:
                type: number
                format: double

components:
  schemas:
    Factura:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fechaEmision:
          type: string
          format: date
        montoTotal:
          type: number
          format: double
        descripcion:
          type: string
        viajeId:
          type: string
        cuentaId:
          type: integer
          format: int64
        usuarioId:
          type: integer
          format: int64
